CREATE SEQUENCE SEQ_SSE_JSON;

CREATE TABLE SSE_JSON
(
  id      BIGINT NOT NULL,
  created TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  handled TIMESTAMP(0) WITH TIME ZONE,
  report  JSONB,
  CONSTRAINT SSE_JSON_PKEY PRIMARY KEY (id)
)