CREATE SEQUENCE SEQ_SSE_REPORT_CONTAINER;

CREATE TABLE SSE_REPORT_CONTAINER
(
  id      BIGINT NOT NULL,
  created TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  handled TIMESTAMP(0) WITH TIME ZONE,
  report  JSONB,
  CONSTRAINT SSE_REPORT_CONTAINER_PKEY PRIMARY KEY (id)
)