CREATE TABLE SSE_SITE_TYPE
(
  TYPE TEXT PRIMARY KEY
);

INSERT INTO SSE_SITE_TYPE(TYPE) VALUES ('FIXED');
INSERT INTO SSE_SITE_TYPE(TYPE) VALUES ('FLOATING');

ALTER TABLE SSE_REPORT ADD COLUMN SITE_TYPE TEXT REFERENCES SSE_SITE_TYPE(TYPE);

-- Foreign key index
CREATE INDEX SSE_REPORT_SITE_TYPE_FKEY_I ON SSE_REPORT USING BTREE (site_type);