CREATE SEQUENCE SEQ_SSE_TLSC_REPORT;

CREATE TABLE SSE_TLSC_REPORT
(
  id      BIGINT NOT NULL,
  created TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  handled TIMESTAMP(0) WITH TIME ZONE,
  report  JSONB,
  CONSTRAINT SSE_TLSC_REPORT_PKEY PRIMARY KEY (id)
)