package fi.livi.digitraffic.meri.model;

public enum DataSource {

    SSE_DATA,

    PORT_CALL,
    PORT_CALL_VESSEL_DETAIL,
    PORT_CALL_LOCATION,
    PORT_CALL_CODE_DESCRIPTIONS,

    VESSEL_DETAIL,
    VESSEL_LOCATION,

    WINTER_NAVIGATION_PORT,
    WINTER_NAVIGATION_VESSEL,
    WINTER_NAVIGATION_DIRWAY,

    NAUTICAL_WARNING,

    BRIDGE_LOCK_DISRUPTION,

    ATON_FAULTS
}
