package fi.livi.digitraffic.meri.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import org.hibernate.annotations.Immutable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import fi.livi.digitraffic.meri.model.AISMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@JsonIgnoreProperties("timestampExternal")
@Entity
@Immutable
@ApiModel(description="Vessel location model")
public class VesselLocation {
    @Id
    @ApiModelProperty(value = "Maritime Mobile Service Identity", required = true)
    private int mmsi;

    @ApiModelProperty(value = "X-coordinate (longitude) in ETRS89 (EUREF-FIN)", required = true)
    private double x;

    @ApiModelProperty(value = "Y-coordinate (latitude) in ETRS89 (EUREF-FIN)", required = true)
    private double y;

    @ApiModelProperty(value = "Speed over ground in 1/10 knot steps ", allowableValues = "range[0,1022]", required = true)
    private double sog;

    @ApiModelProperty(value = "Course over ground in 1/10 = (0-3599). 3600 = not available", allowableValues = "range[0,3600]", required = true)
    private double cog;

    @ApiModelProperty(value = "Navigational status", allowableValues = "range[0,15]", required = true)
    private int navStat;

    @ApiModelProperty(value = "Rate of turn", allowableValues = "range[-128,127]", required = true)
    private int rot;

    @ApiModelProperty(value = "Position accuracy, 1 = high, 0 = low", allowableValues = "0, 1", required = true)
    private boolean posAcc;

    @ApiModelProperty(value = "Receiver autonomous integrity monitoring (RAIM) flag of electronic position fixing device", allowableValues = "0, 1", required = true)
    private boolean raim;

    @ApiModelProperty(value = "Degrees (0-359) (511 indicates not available = default)", allowableValues = "range[0,359], 511", required = false)
    private Integer heading;

    @ApiModelProperty(value = "UTC second when the report was generated by the electronic position system", allowableValues = "range[0,59],60,61,62,63", required = true)
    private long timestamp;

    @ApiModelProperty(value = "Location record timestamp in milliseconds from Unix epoch.", required = true)
    @Column(name = "timestamp_ext")
    private long timestampExternal;

    public  VesselLocation() {
        // for hibernate
    }

    public VesselLocation(final AISMessage ais) {
        this.mmsi = ais.attributes.mmsi;
        this.timestampExternal = ais.attributes.timestampExternal;
        this.x = ais.geometry.x;
        this.y = ais.geometry.y;
        this.sog = ais.attributes.sog;
        this.cog = ais.attributes.cog;
        this.navStat = ais.attributes.navStat;
        this.rot = ais.attributes.rot;
        this.raim = ais.attributes.raim == 1;
        this.timestamp = ais.attributes.timestamp;
        this.posAcc = ais.attributes.posAcc == 1;
        this.heading = ais.attributes.heading;
    }

    public int getMmsi() {
        return mmsi;
    }

    public void setMmsi(final int mmsi) {
        this.mmsi = mmsi;
    }

    public double getX() {
        return x;
    }

    public void setX(final double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(final double y) {
        this.y = y;
    }

    public double getSog() {
        return sog;
    }

    public void setSog(final double sog) {
        this.sog = sog;
    }

    public double getCog() {
        return cog;
    }

    public void setCog(final double cog) {
        this.cog = cog;
    }

    public int getNavStat() {
        return navStat;
    }

    public void setNavStat(final int navStat) {
        this.navStat = navStat;
    }

    public int getRot() {
        return rot;
    }

    public void setRot(final int rot) {
        this.rot = rot;
    }

    public boolean isPosAcc() {
        return posAcc;
    }

    public void setPosAcc(final boolean posAcc) {
        this.posAcc = posAcc;
    }

    public boolean isRaim() {
        return raim;
    }

    public void setRaim(final boolean raim) {
        this.raim = raim;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(final long timestamp) {
        this.timestamp = timestamp;
    }

    public long getTimestampExternal() {
        return timestampExternal;
    }

    public void setTimestampExternal(final long timestampExternal) {
        this.timestampExternal = timestampExternal;
    }

    public Integer getHeading() {
        return heading;
    }

    public void setHeading(final Integer heading) {
        this.heading = heading;
    }
}
