package fi.livi.digitraffic.meri.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import org.hibernate.annotations.Immutable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import fi.livi.digitraffic.meri.model.AISMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@JsonIgnoreProperties("timestampExternal")
@Entity
@Immutable
@ApiModel(description="Vessel location model")
public class VesselLocation {
    @Id
    @ApiModelProperty(value = "Maritime Mobile Service Identity", required = true)
    private int mmsi;

    @ApiModelProperty(value = "X-coordinate (longitude) in ETRS89 (EUREF-FIN)", required = true)
    private double x;

    @ApiModelProperty(value = "Y-coordinate (latitude) in ETRS89 (EUREF-FIN)", required = true)
    private double y;

    @ApiModelProperty(value = "Speed in knots", required = true)
    private double sog;

    @ApiModelProperty(value = "Course in TODO", required = true)
    private double cog;

    private int navStat;

    private int rot;

    private boolean posAcc;

    private boolean raim;

    @ApiModelProperty(value = "UTC second when the report was generated by the electronic position system", required = true)
    private long timestamp;

    @ApiModelProperty(value = "Location record timestamp in milliseconds from Unix epoch.", required = true)
    @Column(name = "timestamp_ext")
    private long timestampExternal;

    public  VesselLocation() {
        // for hibernate
    }

    public VesselLocation(final AISMessage ais) {
        this.mmsi = ais.attributes.mmsi;
        this.timestampExternal = ais.attributes.timestampExternal;
        this.x = ais.geometry.x;
        this.y = ais.geometry.y;
        this.sog = ais.attributes.sog;
        this.cog = ais.attributes.cog;
        this.navStat = ais.attributes.navStat;
        this.rot = ais.attributes.rot;
        this.raim = ais.attributes.raim == 1;
        this.timestamp = ais.attributes.timestamp;
        this.posAcc = ais.attributes.posAcc == 1;
    }

    public int getMmsi() {
        return mmsi;
    }

    public void setMmsi(int mmsi) {
        this.mmsi = mmsi;
    }

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }

    public double getSog() {
        return sog;
    }

    public void setSog(double sog) {
        this.sog = sog;
    }

    public double getCog() {
        return cog;
    }

    public void setCog(double cog) {
        this.cog = cog;
    }

    public int getNavStat() {
        return navStat;
    }

    public void setNavStat(int navStat) {
        this.navStat = navStat;
    }

    public int getRot() {
        return rot;
    }

    public void setRot(int rot) {
        this.rot = rot;
    }

    public boolean isPosAcc() {
        return posAcc;
    }

    public void setPosAcc(boolean posAcc) {
        this.posAcc = posAcc;
    }

    public boolean isRaim() {
        return raim;
    }

    public void setRaim(boolean raim) {
        this.raim = raim;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public long getTimestampExternal() {
        return timestampExternal;
    }

    public void setTimestampExternal(long timestampExternal) {
        this.timestampExternal = timestampExternal;
    }
}
