package fi.livi.digitraffic.meri.model.ais;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "GeoJSON Properties object")
public class VesselLocationProperties implements Serializable {
    @ApiModelProperty(value = "Speed over ground in 1/10 knot steps ", allowableValues = "range[0,1022]", required = true)
    public final double sog;

    @ApiModelProperty(value = "Course over ground in 1/10 = (0-3599). 3600 = not available", allowableValues = "range[0,3600]", required = true)
    public final double cog;

    @ApiModelProperty(value = "Navigational status", allowableValues = "range[0,15]", required = true)
    public final int navStat;

    @ApiModelProperty(value = "Rate of turn", allowableValues = "range[-128,127]", required = true)
    public final int rot;

    @ApiModelProperty(value = "Position accuracy, 1 = high, 0 = low", allowableValues = "0, 1", required = true)
    public final boolean posAcc;

    @ApiModelProperty(value = "Receiver autonomous integrity monitoring (RAIM) flag of electronic position fixing device", allowableValues = "0, 1", required = true)
    public final boolean raim;

    @ApiModelProperty(value = "Degrees (0-359) (511 indicates not available = default)", allowableValues = "range[0,359], 511", required = false)
    public final Integer heading;

    @ApiModelProperty(value = "UTC second when the report was generated by the electronic position system", allowableValues = "range[0,59],60,61,62,63", required = true)
    public final long timestamp;

    @ApiModelProperty(value = "Location record timestamp in milliseconds from Unix epoch.", required = true)
    public final long timestampExternal;

    public VesselLocationProperties(double sog, double cog, int navStat, int rot, boolean posAcc, boolean raim, Integer heading, long timestamp,
                                    long timestampExternal) {
        this.sog = sog;
        this.cog = cog;
        this.navStat = navStat;
        this.rot = rot;
        this.posAcc = posAcc;
        this.raim = raim;
        this.heading = heading;
        this.timestamp = timestamp;
        this.timestampExternal = timestampExternal;
    }
}
