name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn install -T1.5C git-commit-id:revision install -e -U -DskipTests=true
      - name: Create Docker network
        working-directory: dbmarine
        run: docker-compose rm db && docker-compose up -d
      - name: Get database IP
        run: echo "db_addr=$(docker inspect dbmarine_db_1 -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}')" >> $GITHUB_ENV
      - name: Prepare test run
        run: cp src/test/resources/application-default.properties.template target/test-classes/application-ci.properties
      - name: Run tests
        run: |
          mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report -e -U -Dmaven.gitcommitid.skip=true -Dspring.jdbc.getParameterType.ignore=true -Dspring.profiles.active=ci -Dquartz.enabled=false -Dmarine.datasource.url=jdbc:postgresql://${{ env.db_addr }}:5432/marine
      - name: Publish test results
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1
        if: success() || failure()
        with:
          name: jUnit tests
          path: "target/surefire-reports/*.xml"
          reporter: java-junit
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Marine build
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}